/* Write JavaScript here */

var funds = [
    {
        "Ref": "1",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Rheumatic Heart Disease screening",
        "ProjectTitleLong": "",
        "Description": "I am a paediatrician with experience in tropical medicine in northern Australia, the Solomon Islands and Fiji. The prevalence of Rheumatic Heart Disease in the Pacific, including Indigenous children in Australia, is amongst the highest in the world, and my project will investigate ways to reduce the burden of this disease. I will examine population screening with echocardiography (ultrasound) to detect the disease before children become sick, and investigate ways to improve patient management.",
        "LeadInvestigator": "Dr Daniel Engelman",
        "CoInvestigators": "",
        "TotalGrantBudget": "$120,671.54",
        "ApplicationYear": "2013",
        "StartYear": "2014",
        "EndYear": "2017",
        "GrantLength": "3",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Postgraduate Scholarships",
        "GrantSubType": "Public Health Postgraduate Scholarship",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1075171",
        "ID": "1075171"
    },
    {
        "Ref": "2",
        "Institute": "James Cook University",
        "Latitude": "-19.32959",
        "Longitude": "146.760907",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Proteins That Trigger Rheumatic Heart Disease",
        "ProjectTitleLong": "Determination of Disease Specific Epitopes in Rheumatic Heart Disease in Australia",
        "Description": "Rheumatic Fever and Rheumatic Heart Disease (RF-RHD) remain a significant cause of illness in Aboriginal communities in Australia. RF-RHD is a complication which follows infection with a specific bacterium. The purpose of this study is to compare the body's response and find out the patterns of antibody and immune cell reactivity to the bacterium and body proteins in RF-RHD patients and controls. It will also enable us to study the mechanisms that initiate the disease process.",
        "LeadInvestigator": "Prof Natkunam Ketheesan",
        "CoInvestigators": "Prof Madeleine Cunningham",
        "TotalGrantBudget": "$374,817.44",
        "ApplicationYear": "2008",
        "StartYear": "2009",
        "EndYear": "2012",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/540419",
        "ID": "540419"
    },
    {
        "Ref": "3",
        "Institute": "University of New South Wales",
        "Latitude": "-33.91741",
        "Longitude": "151.231307",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Rheumatic heart disease in pregnancy",
        "ProjectTitleLong": "A national population-based study of rheumatic heart disease in pregnancy",
        "Description": "Whilst overall a rare disease, Indigenous peoples have disproportionately high rates of rheumatic heart disease (RHD). This study explores the prevalence and distribution of RHD in pregnancy in Australia and New Zealand. It details current management, diagnostic and referral process and risk factors. Key attributes of culturally safe models of care for RHD in pregnancy are explored, particularly as they relate to Indigenous women. Findings will inform policy, guidelines and education resources.",
        "LeadInvestigator": "Prof Elizabeth Sullivan",
        "CoInvestigators": "Prof Jonathan Carapetis, Prof Lisa Jackson Pulver, Prof Michael Peek, Dr Marie Claire Mclintock, Prof Sue Kruske, Dr Warren Walsh",
        "TotalGrantBudget": "$874,013.17",
        "ApplicationYear": "2011",
        "StartYear": "2012",
        "EndYear": "2015",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1024206",
        "ID": "1024206"
    },
    {
        "Ref": "4",
        "Institute": "James Cook University",
        "Latitude": "-19.32959",
        "Longitude": "146.760907",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "New preventive strategy for rheumatic heart disease",
        "ProjectTitleLong": "Development of a preventive strategy for rheumatic heart disease using an experimental model",
        "Description": "Based on animal studies, we aim to demonstrate that theworsening of heart damage seen in patients with rheumatic heart disease (RHD) is due to repeated infections with bacteria (group A streptococci: GAS). The heart damage is caused by continual immune damage to the heart and valves and this has adverse effects on heart function. We will also investigate a novel way to prevent the development of RHD.",
        "LeadInvestigator": "Prof Natkunam Ketheesan",
        "CoInvestigators": "Dr Catherine Rush",
        "TotalGrantBudget": "$370,846.14",
        "ApplicationYear": "2011",
        "StartYear": "2012",
        "EndYear": "2015",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1026753",
        "ID": "1026753"
    },
    {
        "Ref": "5",
        "Institute": "University of Western Australia",
        "Latitude": "-31.981179",
        "Longitude": "115.81991",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Improving delivery of secondary prophylaxis for rheumatic heart disease",
        "ProjectTitleLong": "Improving delivery of secondary prophylaxis for rheumatic heart disease: a stepped-wedge, community-randomised trial",
        "Description": "Rheumatic heart disease (RHD) is a major health problemin Indigenous communities. Continued progress in controlling RHD requires an understanding of how to improve delivery of regular injections of penicillin - secondary prophylaxis (SP). We will evaluate a systems-based approach to improving delivery of SP, using a stepped-wedge trial in 12 communities in NT and Qld. If successful, this model will provide a practical and transferable model.",
        "LeadInvestigator": "Prof Jonathan Carapetis",
        "CoInvestigators": "Prof Graeme Maguire, Dr Vanessa Johnston, Prof Bart Currie, Dr Anna Ralph, Prof Ross Bailie, Ms Adrienne Kirby, Dr Keith Edwards, Prof Alex Brown",
        "TotalGrantBudget": "$1,910,019.79",
        "ApplicationYear": "2011",
        "StartYear": "2012",
        "EndYear": "2015",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1027040",
        "ID": "1027040"
    },
    {
        "Ref": "6",
        "Institute": "Queensland Institute of Medical Research",
        "Latitude": "-27.449561",
        "Longitude": "153.027266",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "The development of a group A streptococcal vaccine and understanding the immunopathogenesis of rheumatic heart disease",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "Dr Colleen Olive",
        "CoInvestigators": "",
        "TotalGrantBudget": "$435,500.00",
        "ApplicationYear": "2002",
        "StartYear": "2003",
        "EndYear": "2007",
        "GrantLength": "4",
        "MainFundingGroup": "People Support",
        "GrantType": "Career Development Fellowships",
        "GrantSubType": "RD Wright Biomedical CDF",
        "PURL": "http://purl.org/au-research/grants/nhmrc/241952",
        "ID": "241952"
    },
    {
        "Ref": "7",
        "Institute": "University of Western Australia",
        "Latitude": "-31.981179",
        "Longitude": "115.81991",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Genetic Associations of Rheumatic Heart Disease in Australian Aboriginal and Torres Strait Islander communities",
        "ProjectTitleLong": "Evaluating the genetic contribution to rheumatic heart disease pathogenesis in Australian Aboriginal and Torres Strait Islander communities",
        "Description": "Rheumatic heart disease is highly prevalent in Aboriginal people in Australia and leads to early cardiac disease. Despite decades of research, the underlying genetic mechanisms for why it occurs are not well understood. We are conducting a genetic study to better understand why some people are susceptible to RHD and others are not. The study will involve substantial Aboriginal leadership and consultation and will be a model for the conduct of genetic studies in Aboriginal populations.",
        "LeadInvestigator": "Prof Jonathan Carapetis",
        "CoInvestigators": "A/Pr Dawn Bessarab, Ms Heather D'Antoine, A/Pr Andrew Steer, Dr Bo Remenyi, Prof Jenefer Blackwell, Prof Paul De Bakker, Prof Ngiare Brown, Dr Steven Tong, Dr Michael Inouye",
        "TotalGrantBudget": "$1,779,529.42",
        "ApplicationYear": "2011",
        "StartYear": "2012",
        "EndYear": "2015",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1023462",
        "ID": "1023462"
    },
    {
        "Ref": "8",
        "Institute": "Queensland Institute of Medical Research",
        "Latitude": "-27.449561",
        "Longitude": "153.027266",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Peptide vaccination to prevent heart disease",
        "ProjectTitleLong": "A dual antigen synthetic peptide subunit vaccine approach to prevent streptococcal associated cardiovascular disease",
        "Description": "Infection with streptococcus is responsible for causingmore than 500,000 deaths each year, the majority of which are due to rheumatic fever and rheumatic heart disease, which contributes to cardiovascular disease. Our research is aimed at the development of a vaccine to prevent heart disease and involves targeting multiple molecules present on the bacterial surface. We will use a novel vaccine delivery system developed in the laboratory, which will enable the vaccine to be delivered nasally.",
        "LeadInvestigator": "Dr Colleen Olive",
        "CoInvestigators": "Prof Carlos Guzman",
        "TotalGrantBudget": "$604,017.00",
        "ApplicationYear": "2009",
        "StartYear": "2010",
        "EndYear": "2013",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/613616",
        "ID": "613616"
    },
    {
        "Ref": "9",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Control of streptococcal disease",
        "ProjectTitleLong": "Prevention of group A streptococcal disease in the developing world: investigating innovative control strategies for rheumatic heart disease and impetigo",
        "Description": "Group A streptococcal diseases, including rheumatic heart disease and impetigo, are major causes of illness globally, mostly in developing countries. This proposal is a comprehensive investigation into new ways of curbing these diseases, including using ultrasound screening for rheumatic heart disease, community wide treatment for impetigo and laboratory testing for new vaccines. The studies will be done in Fiji and will be relevant for other developing countries and for Indigenous Australians.",
        "LeadInvestigator": "A/Pr Andrew Steer",
        "CoInvestigators": "",
        "TotalGrantBudget": "$178,614.57",
        "ApplicationYear": "2010",
        "StartYear": "2011",
        "EndYear": "2012",
        "GrantLength": "1",
        "MainFundingGroup": "People Support",
        "GrantType": "Early Career Fellowships",
        "GrantSubType": "Public Health (Australia) ECF",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1014431",
        "ID": "1014431"
    },
    {
        "Ref": "10",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Global control of group A streptococcal disease",
        "ProjectTitleLong": "The control of group A streptococcal disease in endemic populations",
        "Description": "Group A streptococcal diseases, including rheumatic heart disease, are major causes of illness globally, mostly in developing countries. This proposal is an investigation into how best to tackle control these diseases. It focuses on 1) a novel way to detect rheumatic heart disease in its earliest phases using ultrasound, 2) using a single drug once per year to stop streptococcal skin sores by controlling scabies infestation in whole communities and 3) developing a new vaccine that is applicable across all regions of the world.",
        "LeadInvestigator": "A/Pr Andrew Steer",
        "CoInvestigators": "",
        "TotalGrantBudget": "$410,045.29",
        "ApplicationYear": "2012",
        "StartYear": "2013",
        "EndYear": "2016",
        "GrantLength": "3",
        "MainFundingGroup": "People Support",
        "GrantType": "Career Development Fellowships",
        "GrantSubType": "Population Health CDF",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1052152",
        "ID": "1052152"
    },
    {
        "Ref": "11",
        "Institute": "James Cook University",
        "Latitude": "-19.32959",
        "Longitude": "146.760907",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "ARF and RHD in Indigenous Australians",
        "ProjectTitleLong": "Enhancing the prevention, diagnosis and management of acute rheumatic fever and rheumatic heart disease in Aboriginal Australian and Torres Strait Islander Populations",
        "Description": "I am a health researcher focused on improving the diagnosis and care of rheumatic heart disease (RHD) in Indigenous Australians. I am examining the use of heart ultrasounds to detect the earliest stages of RHD in Indigenous children. Earlier detection can lead to earlier treatment and therefore less heart damage. I also intend to improve care for people with RHD by evaluating health services to determine what factors enhance outcomes for people with RHD.",
        "LeadInvestigator": "Mr Marc Remond",
        "CoInvestigators": "",
        "TotalGrantBudget": "$73,688.26",
        "ApplicationYear": "2011",
        "StartYear": "2011",
        "EndYear": "2014",
        "GrantLength": "3",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Postgraduate Scholarships",
        "GrantSubType": "Public Health Postgraduate Scholarship",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1038200",
        "ID": "1038200"
    },
    {
        "Ref": "12",
        "Institute": "Baker IDI Heart and Diabetes Institute",
        "Latitude": "-37.845644",
        "Longitude": "144.983642",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Rheumatic Fever Follow-up Study (RhFFUS)",
        "ProjectTitleLong": "Rheumatic Fever Follow-up Study (RhFFUS) – determining the optimal clinical response for minor heart valve abnormalities in an Indigenous Australian setting",
        "Description": "Acute rheumatic fever (ARF) and rheumatic heart disease(RHD) are a major health issue for Indigenous Australians. In a previous study heart ultrasounds in Aboriginal and Torres Strait Islander children frequently showed suspicious but not diagnostic changes. RhFFUS (Rheumatic Fever Follow-Up Study) aims to see if these changes are associated with a higher risk of ARF and progression to RHD. If this is the case these high risk children could be identified earlier and offered regular antibiotics to prevent this cause of heart disease.",
        "LeadInvestigator": "Prof Graeme Maguire",
        "CoInvestigators": "Dr Andrew White, Prof David Atkinson",
        "TotalGrantBudget": "$1,394,792.09",
        "ApplicationYear": "2010",
        "StartYear": "2011",
        "EndYear": "2014",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1005951",
        "ID": "1005951"
    },
    {
        "Ref": "13",
        "Institute": "Baker IDI Heart and Diabetes Institute",
        "Latitude": "-37.845644",
        "Longitude": "144.983642",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "How can you mend a broken heart?",
        "ProjectTitleLong": "",
        "Description": "Rheumatic heart disease (RHD) is rare in developed countries except in indigenous populations where there is a shortage of quality health care, overcrowding, poverty and poor nutrition as in remote Australia. Advanced RHD affects the heart valves which can lead to heart failure, an increased risk of stroke and infection of the heart. The aim of this research project will be to inform the development of rational and evidence-based recommendations for the management of advanced RHD.",
        "LeadInvestigator": "Mrs Elizabeth Russell",
        "CoInvestigators": "",
        "TotalGrantBudget": "$81,209.00",
        "ApplicationYear": "2013",
        "StartYear": "2014",
        "EndYear": "2016",
        "GrantLength": "2",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Postgraduate Scholarships",
        "GrantSubType": "Training Scholarship for Aboriginal Health Research",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1074550",
        "ID": "1074550"
    },
    {
        "Ref": "14",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "A new model for rheumatic fever",
        "ProjectTitleLong": "A new model for the pathogenesis of rheumatic fever: superantigen priming of the immune response to group A streptococci",
        "Description": "Acute rheumatic fever (ARF) is now rare in developed countries. However, it remains a major problem in Aboriginal Australians in the NT where the rate of ARF is the highest in the world. This leads to high rates of rheumatic heart disease (up to 3% of individuals in some communities) and a premature mortality of over four times that for developing countries. Immunisation and improved living conditions offer a long-term solution but these remain a distant prospect. In the short and medium term, control of this ARF will partly depend on new and better treatment and prevention strategies. To achieve these goals a deeper understanding of the immune mechanisms underlying this disease is urgently needed. It is known that ARF is caused by an abnormal immune response following streptococcal infection. This leads to the production of cells called T cells that attack the body s own tissues rather than the bacteria itself. This autoimmune disease is responsible for the heart damage that underlies ARF. It is believed that this proces only occurs when susceptible individuals are infected with specific rheumatogenic strains of streptococci. However there are a number of deficiencies in this model and it is proposed that there is an additional factor responsible for the abnormal immune response in ARF. This project will explore the possibility that bacterial toxins called superantigens are the critical missing factor , by studying the immune response in ARF. Superantigens are produced by certain streptococci and staphylococci, and are potent in minute quantities causing widespread activation of the immune system. They have been found to play an important role in a number of autoimmune diseases and the type of immune response found in ARF fits well with that expected if superantigens were involved. If superantigens play an important role in causing the abnormal immune response in ARF then a number of new avenues would open for the treatment and prevention of this disease.",
        "LeadInvestigator": "Prof Nigel Curtis",
        "CoInvestigators": "A/Pr Kumar Visvanathan, Prof Jonathan Carapetis, Prof Roy Robins-Browne, Prof Andrew Kemp",
        "TotalGrantBudget": "$248,820.00",
        "ApplicationYear": "2001",
        "StartYear": "2002",
        "EndYear": "2004",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/216716",
        "ID": "216716"
    },
    {
        "Ref": "15",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Wider health benefits from control of scabies and skin infections",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "Dr Kerry Gaudry",
        "CoInvestigators": "",
        "TotalGrantBudget": "$6,621.25",
        "ApplicationYear": "2004",
        "StartYear": "2005",
        "EndYear": "2005",
        "GrantLength": "0",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Postgraduate Scholarships",
        "GrantSubType": "Training Scholarship for Aboriginal Health Research",
        "PURL": "http://purl.org/au-research/grants/nhmrc/333418",
        "ID": "333418"
    },
    {
        "Ref": "16",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Clinical and genomic aspects of Staphylococcus aureus and other infectious diseases in northern Australia.",
        "ProjectTitleLong": "",
        "Description": "The burden of infectious disease is high in Indigenous populations in northern Australia and patterns of disease differ. My research proposes to deepen our understanding of infectious diseases such as that due to Staphylococcus aureus (golden staph), hepatitis B and influenza by applying cutting-edge technologies (e.g., bacterial genomics) to answer clinically relevant questions. Ultimately I hope to prevent transmission of infections, improve vaccine strategies and find better targets for treatment.",
        "LeadInvestigator": "Dr Steven Tong",
        "CoInvestigators": "",
        "TotalGrantBudget": "$411,767.04",
        "ApplicationYear": "2013",
        "StartYear": "2014",
        "EndYear": "2017",
        "GrantLength": "3",
        "MainFundingGroup": "People Support",
        "GrantType": "Career Development Fellowships",
        "GrantSubType": "RD Wright Biomedical CDF",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1065736",
        "ID": "1065736"
    },
    {
        "Ref": "17",
        "Institute": "Queensland Institute of Medical Research",
        "Latitude": "-27.449561",
        "Longitude": "153.027266",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Diagnostics for drug resistance in scabies",
        "ProjectTitleLong": "",
        "Description": "Scabies is a significant disease of children particularly in indigenous communities. This project is aimed at working out how scabies mites resist medications used to treat them and to design a test for drug resistance. The tools developed in this project will enable the assessment of treatment failures and assist in the development of more sensitive methods for monitoring resistance in the community, including the potential for reversing it.",
        "LeadInvestigator": "Prof James McCarthy",
        "CoInvestigators": "Dr Cielo Pasay, Dr Deborah Holt, A/Pr Shelley Walton",
        "TotalGrantBudget": "$348,931.67",
        "ApplicationYear": "2007",
        "StartYear": "2008",
        "EndYear": "2010",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/496635",
        "ID": "496635"
    },
    {
        "Ref": "18",
        "Institute": "University of Queensland",
        "Latitude": "-27.495431",
        "Longitude": "153.01203",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Developing a safe vaccine against group A streptococci",
        "ProjectTitleLong": "",
        "Description": "Group A streptococcus causes 520,000 deaths each year. A safe and effective vaccine is not commercially available. We have identified new protective candidate antigens, and we seek to undertake critical non-human primate studies to provide further proof-of-concept data. This work will underpin commercial decisions by our industry partner (Sanofi Pasteur) leading to human trials and the development of a safe group A streptococcal vaccine for human use.",
        "LeadInvestigator": "Prof Mark Walker",
        "CoInvestigators": "Prof Istvan Toth, Dr Peter Moyle, Prof Victor Nizet, Prof Guido Silvestri, Dr Michael Batzloff",
        "TotalGrantBudget": "$765,576.24",
        "ApplicationYear": "2013",
        "StartYear": "2014",
        "EndYear": "2015",
        "GrantLength": "1",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Development Grants",
        "GrantSubType": "Development Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1074899",
        "ID": "1074899"
    },
    {
        "Ref": "19",
        "Institute": "Baker IDI Heart and Diabetes Institute",
        "Latitude": "-37.845644",
        "Longitude": "144.983642",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Better care of heart and lung disease for Aboriginal and Torres Strait Islander people in rural and remote Australia",
        "ProjectTitleLong": "Prevention, diagnosis and management of heart and lung disease for Aboriginal and Torres Strait Islander people in rural and remote Australia",
        "Description": "Lung and heart disease are major contributors to the Aboriginal Australian and Torres Strait Islander health gap. This is even more so in remote and regional Australia. This Fellowship will generate new knowledge regarding how best to prevent, diagnose and treat heart and lung disease in this setting. Based in Alice Springs, it will bring together researchers and health care providers across northern and Central Australia and link them with our leading national research institutes.",
        "LeadInvestigator": "Prof Graeme Maguire",
        "CoInvestigators": "",
        "TotalGrantBudget": "$392,704.67",
        "ApplicationYear": "2012",
        "StartYear": "2013",
        "EndYear": "2017",
        "GrantLength": "4",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Research Fellowships",
        "GrantSubType": "Practitioner Fellowship",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1046563",
        "ID": "1046563"
    },
    {
        "Ref": "20",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Drug resistance in scabies",
        "ProjectTitleLong": "Investigating the molecular basis of emerging drug resistance in scabies mites",
        "Description": "Scabies is a disease of the skin caused by the burrowing of the 'itch' mite Sarcoptes scabiei. In remote Aboriginal communities in northern and central Australia up to 60% of children can be infected. Scabies causes intense itching of the skin, resulting in skin damage through scratching, and serious secondary bacterial infections leading to kidney and heart disease. Some remote communities in the NT are documented to have the highest rates of kidney and heart disease in the world. The location of the Menzies School of Health Research in this region where scabies is endemic has enabled us to undertake a number of studies on the disease. Our world first molecular study using microsatellite markers demonstrated that scabies mites on people were genetically distinct from those on dogs. This had important implications in control programs in the communities. Additional work has focused on laboratory studies to monitor the sensitivity of mites to current treatments used in community control programs and for the treatment of crusted scabies, a very severe and debilitating form of the disease. We have reported evidence of increasing resistance of scabies mites to topical 5%permethrin and documented both in vitro and clinical evidence of resistance to oral ivermectin. We now seek support to extend this work to identify at the molecular level the mechanisms of resistance and use this knowledge to design a diagnostic test. This work has both local and global implications. Scabies is a significant disease of children primarily in many indigenous and third world communities, as well as associated with nursing homes and HIV infection. The tools developed in this project will enable the assessment of drug treatment failures and assist in the development of more sensitive methods for monitoring resistance in the community, including the potential for reversing it. This will avoid the current global problems of resistance observed in other organisms such as headlice.",
        "LeadInvestigator": "A/Pr Shelley Walton",
        "CoInvestigators": "Prof Bart Currie, Dr Deborah Holt, Prof James Mccarthy",
        "TotalGrantBudget": "$516,000.00",
        "ApplicationYear": "2003",
        "StartYear": "2004",
        "EndYear": "2006",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/283301",
        "ID": "283301"
    },
    {
        "Ref": "21",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Can skin infection with group A streptococcus cause acute rheumatic fever?",
        "ProjectTitleLong": "",
        "Description": "It is traditionally taught that the cause of acute rheumatic fever (ARF) is always infection of the throat with the bacterium group A streptococcus (GAS). However, in Aboriginal communities of the Top End of the Northern Territory the incidence of ARF is the highest reported in the world, yet GAS is uncommonly isolated from the throat. There is further information to suggest that GAS skin sores may underlie many cases of ARF. If this were proven, it would completely alter the traditional view of the cause of ARF, and have important implications for prevention of ARF around the world. Presently, these approaches focus on diagnosing and treating sore throat, but no country has proven that such a program can be successful in substantially reducing new cases of ARF. If it was known that skin infection could lead to ARF, then countries (including Australia) could emphasise the importance of skin health programs. A further benefit of this knowledge would be to influence GAS vaccine development, which presently is largely focused on the prevention of sore throat. A different possibility has recently been raised - that the cause of ARF may not always be GAS, but instead that the related bacteria GCS and GGS may have the potential to cause this disease. Proof of this hypothesis would even more dramatically alter our understanding of disease causation, prevention, and vaccine development. We propose to determine the cause of ARF in Aboriginal communities by regularly swabbing families of people with a history of ARF, and using genetic fingerprinting of the bacteria from the skin and throat swabs. When cases of ARF occur, we will be able to determine the site and type of infection that precipitated the attack. We will conduct a related study in more communities, in which we will swab family members of people with ARF and of control families (without ARF) to determine the bacteria most commonly isolated from ARF families.",
        "LeadInvestigator": "Prof Jonathan Carapetis",
        "CoInvestigators": "Prof Bart Currie",
        "TotalGrantBudget": "$459,450.00",
        "ApplicationYear": "2002",
        "StartYear": "2003",
        "EndYear": "2005",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/251690",
        "ID": "251690"
    },
    {
        "Ref": "22",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Scabies studies; to understand why a few people suffer a severe form of this disease; and towards making a vaccine.",
        "ProjectTitleLong": "Antigens, Allergens and Immune Responses in Normal and Crusted Scabies",
        "Description": "Scabies (itch mite), a parasitic skin infestation of the mite Sarcoptes scabiei, is a major problem among most children in many Aboriginal communities in Australia, often accompanied by streptococcal infections which cause serious diseases. Our world-first molecular studies utilised variable microsatellite markers to demonstrate that scabies mites on people are genetically distinct from those on dogs. This has important implications in control programs in Aboriginal communities. In our current NHMRC program we have cloned scabies antigens, with the aim of understanding more about immunity, which normally limits infestation from developing to the extreme levels seen in the debilitating disease crusted scabies. Our hypothesis is that crusted scabies is the consequence of an immune deficit in these patients. The first such cloned antigen is the equivalent of a known asthma-inducing allergen from a closely related housedust mite. We seek support to continue this successful program and to extend it to search for candidate vaccine antigens.The development of a vaccine would be a step of major importance in prevention. Recent reports estimate up to 300 million scabies cases worldwide, commonly associated with overcrowding and poverty. We are the first laboratory worldwide to have successfully initiated molecular studies on scabies. We have formed close collaborations with the only laboratory with an animal model (Arlian, USA), and the best group working on epidemiology and control of human scabies (Taplin, USA) and co-published with these groups. It is imperative that our NHMRC support be continued and increased to a level compatible with the importance, potential and achievements so far of this unique program.",
        "LeadInvestigator": "Prof David Kemp",
        "CoInvestigators": "Prof Bart Currie, A/Pr Shelley Walton",
        "TotalGrantBudget": "$302,036.72",
        "ApplicationYear": "2000",
        "StartYear": "2001",
        "EndYear": "2003",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/137205",
        "ID": "137205"
    },
    {
        "Ref": "23",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Investigating the allergic like response in ordinary and crusted scabies",
        "ProjectTitleLong": "Characterisation of immune responses to Sarcoptes scabiei cysteine proteases, group 1 allergen homologues, in scabies",
        "Description": "Scabies, a parasitic skin infestation by the 'itch' mite Sarcoptes scabiei, causes significant health problems for children and adults in many remote Aboriginal communities in Australia. Scabies is often the underlying cause of streptococcal skin infections which can cause serious complications such as kidney and heart disease. Although diagnosed scabies cases can be successfully treated, individuals have often already transmitted the disease to others prior to receiving therapy. A particularly dreadful form of scabies, known as crusted scabies, can develop in a minority of people, in which mites multiply in their millions and the affected person develops severe crusting of the skin. This has resulted in death within 5 years for up to 50% of people with this form of scabies. Scabies mites are scientifically very similar to house dust mites, and they produce cross reactive proteins. Molecular studies in our laboratory have enabled the identification and cloning of a number of scabies molecules with considerable similarity to known house dust mite proteins that cause allergic disease. In this study we propose to focus on a group of scabies proteins with significant identity to the extensively studied Group 1 house dust mite allergens, reported to cause an immune response in 90% of mite allergic people. We propose to use these scabies mite molecules to characterise the immune response in ordinary scabies and compare it to the more severe and debilitating crusted form of the disease. Characterisation of the immune response in scabies will ultimately aid in the development of new treatment for crusted scabies based on immunotherapy. Studies will also investigate for any cross reactivity with the house dust mite group 1 molecules and enable the design of specific immunodiagnositics to distinguish house dust mite allergy from scabies infestation and thus facilitate early diagnosis of scabies carriers and better control of the infestation in endemic communities.",
        "LeadInvestigator": "A/Pr Shelley Walton",
        "CoInvestigators": "Prof Bart Currie, Prof David Kemp, Prof Robyn O'Hehir, E/Pr Jennifer Rolland",
        "TotalGrantBudget": "$465,750.00",
        "ApplicationYear": "2003",
        "StartYear": "2004",
        "EndYear": "2006",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/283300",
        "ID": "283300"
    },
    {
        "Ref": "24",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Investigation of cardiac autoantigens identified by screening a cDNA library with acute rheumatic fever",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "Dr Rebecca Towers",
        "CoInvestigators": "",
        "TotalGrantBudget": "$283,023.79",
        "ApplicationYear": "2006",
        "StartYear": "2007",
        "EndYear": "2011",
        "GrantLength": "4",
        "MainFundingGroup": "People Support",
        "GrantType": "Early Career Fellowships",
        "GrantSubType": "Australian Training ECF for Aboriginal and Torres Strait Islander Health Research",
        "PURL": "http://purl.org/au-research/grants/nhmrc/436034",
        "ID": "436034"
    },
    {
        "Ref": "25",
        "Institute": "Queensland Institute of Medical Research",
        "Latitude": "-27.449561",
        "Longitude": "153.027266",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Scabies mite proteins as targets for the development ofnew therapeutics",
        "ProjectTitleLong": "Scabies mite complement inhibitors as targets for noveltherapeutics",
        "Description": "Scabies and associated bacteria disease (pyoderma) are a significant health burden, with pyoderma implicated in rheumatic fever and heart disease. Investigations of the mechanism underlying scabies and bacteria disease links, identified scabies proteins inhibiting the human complement system. The inhibition prevents mite damage and promotes growth of bacteria. This proposal aims to elucidate the interaction between scabies, bacteria and the human host, in order to design new therapeutics.",
        "LeadInvestigator": "Dr Simone Reynolds",
        "CoInvestigators": "",
        "TotalGrantBudget": "$326,314.32",
        "ApplicationYear": "2012",
        "StartYear": "2013",
        "EndYear": "2017",
        "GrantLength": "4",
        "MainFundingGroup": "People Support",
        "GrantType": "Early Career Fellowships",
        "GrantSubType": "Australian Training ECF for Aboriginal and Torres Strait Islander Health Research",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1054968",
        "ID": "1054968"
    },
    {
        "Ref": "26",
        "Institute": "Queensland Institute of Medical Research",
        "Latitude": "-27.449561",
        "Longitude": "153.027266",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Do scabies mite molecules we have identified help the mites to overcome the human defense?",
        "ProjectTitleLong": "Functional Analysis of Novel Scabies Mite Serpins",
        "Description": "Scabies is caused by microscopic mites burrowing through the skin, causing intense itching and providing prime breeding sites for bacteria. The resulting skin sores are very common among Aboriginal children in Australia leading to extreme levels of rheumatic fever-heart disease and renal failure in Indigenous communities. We have discovered mite products termed Serpins which interfere with the patients defence against the mites and the bacteria and aim to develop therapeutics.",
        "LeadInvestigator": "Dr Katja Fischer",
        "CoInvestigators": "",
        "TotalGrantBudget": "$333,419.45",
        "ApplicationYear": "2009",
        "StartYear": "2010",
        "EndYear": "2013",
        "GrantLength": "3",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "New Investigator Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/613626",
        "ID": "613626"
    },
    {
        "Ref": "27",
        "Institute": "University of Wollongong",
        "Latitude": "-34.405404",
        "Longitude": "150.87843",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Developing new group A streptococcal vaccines.",
        "ProjectTitleLong": "Investigation of the localisation, transport and vaccine potential of group A streptococcal cell surface proteins",
        "Description": "Streptococcus pyogenes (group A streptococcus; GAS) is a bacterium that causes human skin and throat infections as well as highly invasive diseases including necrotising fasciitis. Additionally, serious sequeale, including rheumatic fever and acute glomerulonephritis, may result following repeated infection. We have recently examined the GAS cell wall and identified 23 proteins that are surface exposed, 20 of which are novel. We hypothesise that a number of these surface exposed proteins represent candidate vaccine antigens capable of conferring protective immunity. We therefore propose to examine these surface proteins as components of experimental vaccines against GAS.",
        "LeadInvestigator": "Prof Mark Walker",
        "CoInvestigators": "Prof Gurshuran Chhatwal, Dr Malak Kotb, Prof Victor Nizet, Dr John Aquilina",
        "TotalGrantBudget": "$505,523.48",
        "ApplicationYear": "2005",
        "StartYear": "2006",
        "EndYear": "2008",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/404502",
        "ID": "404502"
    },
    {
        "Ref": "28",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Estimating the burden of group A streptococcal diseasesin Victoria.",
        "ProjectTitleLong": "Estimating the burden of group A streptococcal diseases in Victoria",
        "Description": "Despite the considerable advances in the diagnosis and treatment of group A streptococcal (GAS) diseases made during the last century, the impressive spectrum of infections caused by this organism continues to have a significant impact in developed countries. This spectrum includes diseases that are mild but common (e.g. sore throat, skin sores), rare but very severe (e.g. bloodstream infections, flesh-eating bacteria) and those that are more common in developing countries and the Aboriginal population (e.g. rheumatic fever, kidney disease). Streptococcal sore throat remains one of the most common childhood infections, and severe group A streptococcal diseases are thought to be increasing in incidence in Australia. Yet, there are no accurate data on the incidence and costs of these or other GAS diseases in non-Aboriginal Australians, or in most other populations around the world. It is becoming more urgent to collect this data as numerous vaccine candidates are entering human trials, new approaches to the treatment of sore throat are emerging, and new strategies to treat and control the spread of severe disease are being developed. We propose a comprehensive strategy to measure the incidence, prevalence and costs of each group of GAS diseases. We will follow a group of families for 12 months to detect cases of GAS sore throat and skin sores and measure the impact on the family. We will survey children in schools to estimate the prevalence of skin sores. We will check hospital records to calculate the number of cases of rheumatic fever and kidney disease. And we will maintain surveillance for severe diseases by checking hospital and laboratory records. We will also check to see if family members of people with severe disease have the GAS bacterium in their throats. We will then compile these data into a comprehensive estimate of the burden of disease in Victoria, and estimate the cost-effectiveness of different treatment and prevention strategies.",
        "LeadInvestigator": "Prof Jonathan Carapetis",
        "CoInvestigators": "Prof John Carlin, Prof Nigel Curtis, Prof Terry Nolan",
        "TotalGrantBudget": "$386,760.00",
        "ApplicationYear": "2001",
        "StartYear": "2002",
        "EndYear": "2004",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/216714",
        "ID": "216714"
    },
    {
        "Ref": "29",
        "Institute": "University of Wollongong",
        "Latitude": "-34.405404",
        "Longitude": "150.87843",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Hijacking of human protease by group A streptococci, the flesh eating bacterium",
        "ProjectTitleLong": "Utilisation of the human plasminogen activation system by group A streptococci: contribution to virulence and disease",
        "Description": "Streptococcus pyogenes (group A streptococci; GAS) is abacterium which causes human skin and throat infections as well as highly invasive diseases including the flesh eating disease necrotising fasciitis. Additionally, serious sequelae, including rheumatic fever and acute glomeulonephritis, may result following infection. Such diseases cause high morbidity and mortality in Aboriginal populations and are a continual significant drain on the national health fund. An important mode of invasion by GAS may be related to their ability to capture and activate host plasminogen via surface-associated or secreted plasminogen binding proteins (receptors). Plasminogen can be activated by host activators or secreted GAS streptokinase to the potent enzyme plasmin which is responsible for the degradation of tissue barriers. Thus, GAS may utilise plasmin to destroy tissue barriers and invade host tissues. The characterisation of the interaction between GAS and the plasminogen activation system would clarify the role of this system in invasive disease and provide potential targets for therapeutic intervention.",
        "LeadInvestigator": "Prof Mark Walker",
        "CoInvestigators": "A/Pr Marie Ranson",
        "TotalGrantBudget": "$254,250.00",
        "ApplicationYear": "2003",
        "StartYear": "2004",
        "EndYear": "2006",
        "GrantLength": "2",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/303401",
        "ID": "303401"
    },
    {
        "Ref": "32",
        "Institute": "University of Melbourne",
        "Latitude": "-37.796369",
        "Longitude": "144.961174",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Preparing for group A streptococcal vaccines: epidemiology and immunology of group A streps in Fiji",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "A/Pr Andrew Steer",
        "CoInvestigators": "",
        "TotalGrantBudget": "$105,852.46",
        "ApplicationYear": "2004",
        "StartYear": "2005",
        "EndYear": "2010",
        "GrantLength": "5",
        "MainFundingGroup": "People Support",
        "GrantType": "NHMRC Postgraduate Scholarships",
        "GrantSubType": "Public Health Postgraduate Scholarship",
        "PURL": "http://purl.org/au-research/grants/nhmrc/359353",
        "ID": "359353"
    },
    {
        "Ref": "33",
        "Institute": "Menzies School of Health Research",
        "Latitude": "-12.354448",
        "Longitude": "130.883173",
        "SearchTerm": "Rheumatic Fever - Rheumatic Heart Disease",
        "ProjectTitle": "Disease-causing bacteria in children",
        "ProjectTitleLong": "Mathematical modelling of bacterial carriage in children",
        "Description": "Children exposed to larger numbers of other children are at risk of persistent bacterial infections. Such circumstances explain the high rates of ear and chest infections, and skin sores seen in children in historical times. Changing social circumstances (smaller families, better housing, nutrition and hygiene), as well as the introduction of antibiotics, explain the decline of such infections in affluent communities since the early 20th century. However, even today, in affluent countries, children attending group child care are at high risk of ear infections. As many bacteria are resistant, antibiotics are now much less effective than when they were first introduced. Furthermore, there is a continuing load of infection for children in Aboriginal communities, in PNG and other developing countries, causing hearing loss, chronic respiratory problems, and heart disease and renal disease in later life. Using data previously collected from other studies in Indigenous communities and children in child care, mathematical models allow us to ask what if?, and answer important public health questions: 1. What environmental and public health measures can reduce the cycle of cross-infection in child-care and high-risk populations? 2. What coverage rates with pneumococcal vaccine will eliminate the vaccine-specific bacteria from child care centres, from the wider community, and from high risk populations? 3. Will infections with bacteria not covered by vaccine then increase? 4. Will the resistant bacteria tend to disappear if antibiotic use is restricted? 5. Under what circumstances will antibiotics help to control infection? The modelling will promote understanding of the social and health costs of bacterial infection in Aboriginal communities and child care and use educational scenarios to promote uptake of the most cost-effective and socially acceptable interventions.",
        "LeadInvestigator": "A/Pr Allen Cheng",
        "CoInvestigators": "Prof Jonathan Carapetis, Prof Bart Currie, Prof John Mathews, Prof Amanda Leach",
        "TotalGrantBudget": "$421,746.00",
        "ApplicationYear": "2006",
        "StartYear": "2007",
        "EndYear": "2008",
        "GrantLength": "1",
        "MainFundingGroup": "Research Support",
        "GrantType": "NHMRC Project Grants",
        "GrantSubType": "Standard Project Grant",
        "PURL": "http://purl.org/au-research/grants/nhmrc/436009",
        "ID": "436009"
    },
    {
        "Ref": "34",
        "Institute": "University of Western Australia",
        "Latitude": "-31.981179",
        "Longitude": "115.81991",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "The END RHD CRE: Developing an endgame for rheumatic heart disease in Australia",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "Prof Jonathan Carapetis",
        "CoInvestigators": "Prof Bart Currie, Prof Graeme Maguire, Prof Dawn Bessarab, Dr Dan McAullay, Ms Heather D’Antoine, Prof Alex Brown, Prof Karen Edmond, A/Prof Andrew Steer, Prof Nicholas de Klerk, As/Prof Vicki Krause, Prof David Atkinson, Dr Gavin Wheaton, Dr Thomas Snelling, Dr Anna Ralph, Dr Stephanie Trust, Ms Claire Boardman, Dr Rosemary Wyber, Ms Samantha Colquhoun, Prof Christopher Reid\n",
        "TotalGrantBudget": "$2,496,816.00",
        "ApplicationYear": "2014",
        "StartYear": "2015",
        "EndYear": "2019",
        "GrantLength": "4",
        "MainFundingGroup": "",
        "GrantType": "Centre for Research Excellence",
        "GrantSubType": "Centre for Research Excellence - Population Health",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1080401 ",
        "ID": "1080401"
    },
    {
        "Ref": "35",
        "Institute": "Murdoch Childrens Research Institute",
        "Latitude": "-37.793747",
        "Longitude": "144.949123",
        "SearchTerm": "Rheumatic Heart Disease",
        "ProjectTitle": "Investigation of the epidemiology and care of rheumatic heart disease patients in resource poor settings and at risk populations",
        "ProjectTitleLong": "",
        "Description": "",
        "LeadInvestigator": "Ms Samantha Colquhoun ",
        "CoInvestigators": "",
        "TotalGrantBudget": "$188,787.52",
        "ApplicationYear": "2014",
        "StartYear": "2015",
        "EndYear": "2018",
        "GrantLength": "3",
        "MainFundingGroup": "People Support",
        "GrantType": "Early Career Fellowships",
        "GrantSubType": "Health Professional Research ECF",
        "PURL": "http://purl.org/au-research/grants/nhmrc/1091628",
        "ID": "1091628"
    }
];

var southWest = L.latLng(),
    northEast = L.latLng(),
    bounds = L.latLngBounds(southWest, northEast); 

var map = L.map('map')
    .setView([-27.959878, 134.214663], 4)
    .setMaxBounds(bounds);

var allMarkers = L.layerGroup();
var curMarkers = L.layerGroup();
var fltrGrpPeople = L.layerGroup();
var fltrGrpResearch = L.layerGroup();

   
mapLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>';
L.tileLayer(
    'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; ' + mapLink + ' Contributors',
    maxZoom: 9,
    minZoom: 4
    }).addTo(map);
    

//loop for data to add markers, styling and pop-ups
$.each(funds, function (index, fund) {
    // ---- Making the Marker ----
var number = Number(fund.TotalGrantBudget.replace(/[^0-9\.]+/g,""));
var radius = number/500000*10;
    var fundMarker = L.circleMarker(L.latLng(fund.Latitude, fund.Longitude));
	fundMarker.setRadius(radius);
fundMarker.setStyle({
    'color' : '#fff',
    'fillOpacity' : 0.8,
    'fillColor' : (function () {
        if (fund.TotalGrantBudget < 100000) {
            return "#edf8e9";
        } else if (fund.TotalGrantBudget  < 200000) {
            return "#bae4b3";
        } else if (fund.TotalGrantBudget < 500000) {
            return "#74c476";
        } else if (fund.TotalGrantBudget < 1000000) {
            return "#31a354";
        } else {
            return "#006d2c";
        }	
    }())
});

var fundPopup = L.popup();
fundPopup.setContent(
  "<strong>" + fund.ProjectTitle + "</strong><br/>" + 
  " (" + fund.StartYear + " to " + fund.EndYear + ")<br/><br/>" + 
  "Lead Investigator: " + fund.LeadInvestigator + "<br/>" +
  "Total Grant Budget: " + fund.TotalGrantBudget + "<br/>" +
  "<a target=\'_blank\' href=\'" + fund.PURL + "\'> More Information about project </a>"
  
);

fundMarker.bindPopup(fundPopup);


allMarkers.addLayer(fundMarker);
curMarkers.addLayer(fundMarker);


if (fund.MainFundingGroup === "Research Support") {
    fltrGrpResearch.addLayer(fundMarker);
}

if (fund.MainFundingGroup === "People Support") {
    fltrGrpPeople.addLayer(fundMarker);
}

});

$('#causes').buttonset();

map.addLayer(curMarkers);

function filterData () {
    curMarkers.clearLayers();   //remove current markers
    allMarkers.eachLayer(function (layer) { //logical test to determine what markers to add to map
        if (
              ( 
                ($("input[id='type_research']:checked").length > 0 && fltrGrpResearch.hasLayer(layer)) || 
                ($("input[id='type_people']:checked").length > 0 && fltrGrpPeople.hasLayer(layer))
              )
           ) {
            curMarkers.addLayer(layer);
        }
    });
}

$("#type_research").change(filterData);
$("#type_people").change(filterData); 
   
